name: harbor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pip:
    - aiohttp>=3.8.0
    - aiortc>=1.6.0
    - av>=10.0.0
    - numpy>=1.24.0
    # Optional dependencies for Raspberry Pi
    # Uncomment these when deploying to actual Pi hardware:
    # - picamera2
    # - gpiozero

  